"""Deterministic fake provider adapter for tests and demos."""

from app.domain.messages import ContentBlock
from app.domain.models import ModelRequest
from app.domain.responses import ModelResponse, TokenUsage


class FakeProvider:
    """Provider adapter that returns deterministic normalized responses."""

    async def generate(self, model: str, request: ModelRequest) -> ModelResponse:
        """Return a normalized response without calling a live provider."""
        prompt_text = " ".join(
            block.text or ""
            for message in request.messages
            for block in message.content
            if block.text is not None
        )
        structured: dict[str, object] = {
            "summary": "Deterministic review generated by the fake provider.",
            "risk_level": "medium" if "payment" in prompt_text.lower() else "low",
            "findings": [
                {
                    "title": "Review generated offline",
                    "severity": "info",
                    "explanation": "The fake provider returned a stable structured response.",
                }
            ],
        }
        prompt_tokens = max(1, len(prompt_text.split()))
        completion_tokens = 24
        return ModelResponse(
            content=[ContentBlock.json_block(structured)],
            tool_calls=[],
            usage=TokenUsage(
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=prompt_tokens + completion_tokens,
            ),
            stop_reason="stop",
            provider_metadata={
                "provider": "fake",
                "model": model,
                "deterministic": True,
            },
        )
